// react_tranning/src/components/UI/select/Myselect.jsx
import React from 'react';

const Myselect = ({option, defaultValue, value, onChange} ) => {
    return (
        <select value={value} onChange={e =>onChange(e.target.value)}>
            <option disabled value=''>{defaultValue}</option>
            {option.map(option => (
                <option key={option.value} value={option.value}>{option.name}</option>
            ))}
        </select>
    );
};

export default Myselect;

// vue_list/src/components/UI/mySelect.vue
<template>
    <select :value="modelValue" @change="chancgeOption">
        <option disabled value="">Выберите из списка</option>
        <option v-for="option in options"
        :key="option.value"
        :value="option.value"
        >{{ option.name }}</option>
    </select>

</template>

<script>
export default {
    name:'my-select',
    props:{
        modelValue:{
            type: String,
        },
        options:{
            type: Array,
            default: ()=>[]
        }
    },
    methods:{
        chancgeOption(event){
            this.$emit('update:modelValue', event.target.value)
        }
    }

}
</script>

<style>

</style>
